# Generated by Django 5.1.7 on 2025-06-24 07:12

import django.db.models.deletion
from django.db import migrations, models

import apps.utils.get_upload_path


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("lathe_machine", "Tokarlik dastgohi"),
                            ("welding_equipment", "Payvandlash uskunalari"),
                            ("heating_boiler", "Isitish qozoni"),
                            ("pressure_vessel", "Yuk ko'taruvchi kranlar"),
                            ("lifting_crane", "Bosim ostida sig'imlar"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HeatingBoiler",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.utils.get_upload_path.get_upload_path,
                        verbose_name="Rasm",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Korxona nomi"
                    ),
                ),
                (
                    "detail_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Detal nomi"
                    ),
                ),
                (
                    "manufacture_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ishlab chiqarilgan yili"
                    ),
                ),
                (
                    "factory_number",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Zavod raqami"
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Qayd raqami"
                    ),
                ),
                (
                    "installation_location",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="O‘rnatilgan joyi"
                    ),
                ),
                (
                    "technical_condition",
                    models.CharField(
                        blank=True,
                        choices=[("working", "Soz"), ("faulty", "Nosoz")],
                        default="working",
                        max_length=50,
                        verbose_name="Texnik holati",
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Yoqilg‘i turi"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="O'zgartirilgan vaqti"
                    ),
                ),
            ],
            options={
                "verbose_name": "Isitish qozoni",
                "verbose_name_plural": "Isitish qozonlari",
            },
            bases=("equipment.equipment", models.Model),
        ),
        migrations.CreateModel(
            name="LatheMachine",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.utils.get_upload_path.get_upload_path,
                        verbose_name="Rasm",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Korxona nomi"
                    ),
                ),
                (
                    "detail_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Detal nomi"
                    ),
                ),
                (
                    "manufacture_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ishlab chiqarilgan yili"
                    ),
                ),
                (
                    "factory_number",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Zavod raqami"
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Qayd raqami"
                    ),
                ),
                (
                    "installation_location",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="O‘rnatilgan joyi"
                    ),
                ),
                (
                    "technical_condition",
                    models.CharField(
                        blank=True,
                        choices=[("working", "Soz"), ("faulty", "Nosoz")],
                        default="working",
                        max_length=50,
                        verbose_name="Texnik holati",
                    ),
                ),
                (
                    "is_conserved",
                    models.BooleanField(
                        default=False, verbose_name="Konservatsiyaga olish"
                    ),
                ),
                (
                    "conservation_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Konservatsiya sababi"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Tavsiyalar"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="O'zgartirilgan vaqti"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tokarlik dastgohi",
                "verbose_name_plural": "Tokarlik dastgohlari",
            },
            bases=("equipment.equipment", models.Model),
        ),
        migrations.CreateModel(
            name="LiftingCrane",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.utils.get_upload_path.get_upload_path,
                        verbose_name="Rasm",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Korxona nomi"
                    ),
                ),
                (
                    "detail_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Detal nomi"
                    ),
                ),
                (
                    "manufacture_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ishlab chiqarilgan yili"
                    ),
                ),
                (
                    "factory_number",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Zavod raqami"
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Qayd raqami"
                    ),
                ),
                (
                    "installation_location",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="O‘rnatilgan joyi"
                    ),
                ),
                (
                    "technical_condition",
                    models.CharField(
                        blank=True,
                        choices=[("working", "Soz"), ("faulty", "Nosoz")],
                        default="working",
                        max_length=50,
                        verbose_name="Texnik holati",
                    ),
                ),
                (
                    "under_crane_path_length",
                    models.CharField(
                        max_length=100, verbose_name="Kran osti yo‘li uzunligi"
                    ),
                ),
                (
                    "crane_width_length",
                    models.CharField(max_length=100, verbose_name="Kran eni uzunligi"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="O'zgartirilgan vaqti"
                    ),
                ),
            ],
            options={
                "verbose_name": "Yuk ko'tarish krani",
                "verbose_name_plural": "Yuk ko'tarish kranlari",
            },
            bases=("equipment.equipment", models.Model),
        ),
        migrations.CreateModel(
            name="PressureVessel",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.utils.get_upload_path.get_upload_path,
                        verbose_name="Rasm",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Korxona nomi"
                    ),
                ),
                (
                    "detail_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Detal nomi"
                    ),
                ),
                (
                    "manufacture_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ishlab chiqarilgan yili"
                    ),
                ),
                (
                    "factory_number",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Zavod raqami"
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Qayd raqami"
                    ),
                ),
                (
                    "installation_location",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="O‘rnatilgan joyi"
                    ),
                ),
                (
                    "technical_condition",
                    models.CharField(
                        blank=True,
                        choices=[("working", "Soz"), ("faulty", "Nosoz")],
                        default="working",
                        max_length=50,
                        verbose_name="Texnik holati",
                    ),
                ),
                (
                    "category_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Sig‘imning kategoriyasi",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="O'zgartirilgan vaqti"
                    ),
                ),
            ],
            options={
                "verbose_name": "Bosim ostida sig'im",
                "verbose_name_plural": "Bosim ostida sig'imlar",
            },
            bases=("equipment.equipment", models.Model),
        ),
        migrations.CreateModel(
            name="WeldingEquipment",
            fields=[
                (
                    "equipment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="equipment.equipment",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.utils.get_upload_path.get_upload_path,
                        verbose_name="Rasm",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Korxona nomi"
                    ),
                ),
                (
                    "detail_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Detal nomi"
                    ),
                ),
                (
                    "manufacture_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ishlab chiqarilgan yili"
                    ),
                ),
                (
                    "factory_number",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Zavod raqami"
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Qayd raqami"
                    ),
                ),
                (
                    "installation_location",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="O‘rnatilgan joyi"
                    ),
                ),
                (
                    "technical_condition",
                    models.CharField(
                        blank=True,
                        choices=[("working", "Soz"), ("faulty", "Nosoz")],
                        default="working",
                        max_length=50,
                        verbose_name="Texnik holati",
                    ),
                ),
                (
                    "is_conserved",
                    models.BooleanField(
                        default=False, verbose_name="Konservatsiyaga olish"
                    ),
                ),
                (
                    "conservation_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Konservatsiya sababi"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="O'zgartirilgan vaqti"
                    ),
                ),
            ],
            options={
                "verbose_name": "Payvandlash qurilmasi",
                "verbose_name_plural": "Payvandlash qurilmalari",
            },
            bases=("equipment.equipment", models.Model),
        ),
    ]
