# Generated by Django 5.1.7 on 2025-04-18 05:25

import apps.utils.get_upload_path
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatingBoiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.utils.get_upload_path.get_upload_path, verbose_name='Rasm')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Korxona nomi')),
                ('detail_name', models.CharField(blank=True, max_length=255, verbose_name='Detal nomi')),
                ('manufacture_date', models.CharField(blank=True, verbose_name='Ishlab chiqarilgan yili')),
                ('factory_number', models.CharField(blank=True, max_length=255, verbose_name='Zavod raqami')),
                ('registration_number', models.CharField(blank=True, max_length=255, verbose_name='Qayd raqami')),
                ('installation_location', models.CharField(blank=True, max_length=255, verbose_name='O‘rnatilgan joyi')),
                ('technical_condition', models.CharField(blank=True, choices=[('working', 'Soz'), ('faulty', 'Nosoz')], default='working', max_length=50, verbose_name='Texnik holati')),
                ('external_internal_inspection_date', models.DateField(blank=True, verbose_name='Tashqi va ichki ko‘rik sanasi')),
                ('washing_testing_date', models.DateField(blank=True, null=True, verbose_name='Yuvish va sinovdan o‘tkazish sanasi')),
                ('manometer_calibration_date', models.DateField(blank=True, null=True, verbose_name='Manometrlarni qiyoslash sanasi')),
                ('fuel_type', models.CharField(blank=True, max_length=100, verbose_name='Yoqilg‘i turi')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Javobgar shaxs')),
            ],
            options={
                'verbose_name': 'Isitish qozoni',
                'verbose_name_plural': 'Isitish qozonlari',
            },
        ),
        migrations.CreateModel(
            name='LatheMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.utils.get_upload_path.get_upload_path, verbose_name='Rasm')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Korxona nomi')),
                ('detail_name', models.CharField(blank=True, max_length=255, verbose_name='Detal nomi')),
                ('manufacture_date', models.CharField(blank=True, verbose_name='Ishlab chiqarilgan yili')),
                ('factory_number', models.CharField(blank=True, max_length=255, verbose_name='Zavod raqami')),
                ('registration_number', models.CharField(blank=True, max_length=255, verbose_name='Qayd raqami')),
                ('installation_location', models.CharField(blank=True, max_length=255, verbose_name='O‘rnatilgan joyi')),
                ('technical_condition', models.CharField(blank=True, choices=[('working', 'Soz'), ('faulty', 'Nosoz')], default='working', max_length=50, verbose_name='Texnik holati')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name="Texnik ko'rik sanasi")),
                ('next_maintenance', models.DateField(blank=True, null=True, verbose_name='Keyingi texnik ko‘rik sanasi')),
                ('is_conserved', models.BooleanField(default=False, verbose_name='Konservatsiyaga olish')),
                ('conservation_reason', models.TextField(blank=True, null=True, verbose_name='Konservatsiya sababi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Tavsiyalar')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Javobgar shaxs')),
            ],
            options={
                'verbose_name': 'Tokarlik dastgohi',
                'verbose_name_plural': 'Tokarlik dastgohlari',
            },
        ),
        migrations.CreateModel(
            name='LiftingCrane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.utils.get_upload_path.get_upload_path, verbose_name='Rasm')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Korxona nomi')),
                ('detail_name', models.CharField(blank=True, max_length=255, verbose_name='Detal nomi')),
                ('manufacture_date', models.CharField(blank=True, verbose_name='Ishlab chiqarilgan yili')),
                ('factory_number', models.CharField(blank=True, max_length=255, verbose_name='Zavod raqami')),
                ('registration_number', models.CharField(blank=True, max_length=255, verbose_name='Qayd raqami')),
                ('installation_location', models.CharField(blank=True, max_length=255, verbose_name='O‘rnatilgan joyi')),
                ('technical_condition', models.CharField(blank=True, choices=[('working', 'Soz'), ('faulty', 'Nosoz')], default='working', max_length=50, verbose_name='Texnik holati')),
                ('under_crane_path_length', models.CharField(max_length=100, verbose_name='Kran osti yo‘li uzunligi')),
                ('crane_width_length', models.CharField(max_length=100, verbose_name='Kran eni uzunligi')),
                ('full_inspection_date', models.DateField(blank=True, null=True, verbose_name='To‘liq texnik ko‘rik sanasi')),
                ('partial_inspection_date', models.DateField(blank=True, null=True, verbose_name='Qisman texnik ko‘rik sanasi')),
                ('next_full_inspection_date', models.DateField(blank=True, null=True, verbose_name='Keyingi to‘liq texnik ko‘rik sanasi')),
                ('next_lab_test_date', models.DateField(blank=True, null=True, verbose_name='Keyingi laboratoriya tekshiruvi sanasi')),
                ('next_leveling_date', models.DateField(blank=True, null=True, verbose_name='Keyingi nivelirovka sanasi')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Javobgar shaxs')),
            ],
            options={
                'verbose_name': "Yuk ko'tarish krani",
                'verbose_name_plural': "Yuk ko'tarish kranlari",
            },
        ),
        migrations.CreateModel(
            name='PressureVessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.utils.get_upload_path.get_upload_path, verbose_name='Rasm')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Korxona nomi')),
                ('detail_name', models.CharField(blank=True, max_length=255, verbose_name='Detal nomi')),
                ('manufacture_date', models.CharField(blank=True, verbose_name='Ishlab chiqarilgan yili')),
                ('factory_number', models.CharField(blank=True, max_length=255, verbose_name='Zavod raqami')),
                ('registration_number', models.CharField(blank=True, max_length=255, verbose_name='Qayd raqami')),
                ('installation_location', models.CharField(blank=True, max_length=255, verbose_name='O‘rnatilgan joyi')),
                ('technical_condition', models.CharField(blank=True, choices=[('working', 'Soz'), ('faulty', 'Nosoz')], default='working', max_length=50, verbose_name='Texnik holati')),
                ('internal_inspection_date', models.DateField(blank=True, null=True, verbose_name='Ichki ko‘rik sanasi')),
                ('hydraulic_test_date', models.DateField(blank=True, null=True, verbose_name='Gidravlik sinov sanasi')),
                ('overpressure_protection_check_date', models.DateField(blank=True, null=True, verbose_name='Ortiqcha bosimdan saqlovchi qurilma sanasi')),
                ('manometer_calibration_date', models.DateField(blank=True, null=True, verbose_name='Manometrlarni qiyoslash sanasi')),
                ('next_internal_inspection_date', models.DateField(blank=True, null=True, verbose_name='Keyingi ichki ko‘rik sanasi')),
                ('next_hydraulic_test_date', models.DateField(blank=True, null=True, verbose_name='Keyingi gidravlik sinov sanasi')),
                ('category_name', models.CharField(blank=True, max_length=100, verbose_name='Kategoriya nomi')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Javobgar shaxs')),
            ],
            options={
                'verbose_name': "Bosim ostida sig'im",
                'verbose_name_plural': "Bosim ostida sig'imlar",
            },
        ),
        migrations.CreateModel(
            name='WeldingEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.utils.get_upload_path.get_upload_path, verbose_name='Rasm')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Korxona nomi')),
                ('detail_name', models.CharField(blank=True, max_length=255, verbose_name='Detal nomi')),
                ('manufacture_date', models.CharField(blank=True, verbose_name='Ishlab chiqarilgan yili')),
                ('factory_number', models.CharField(blank=True, max_length=255, verbose_name='Zavod raqami')),
                ('registration_number', models.CharField(blank=True, max_length=255, verbose_name='Qayd raqami')),
                ('installation_location', models.CharField(blank=True, max_length=255, verbose_name='O‘rnatilgan joyi')),
                ('technical_condition', models.CharField(blank=True, choices=[('working', 'Soz'), ('faulty', 'Nosoz')], default='working', max_length=50, verbose_name='Texnik holati')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name="Texnik ko'rik sanasi")),
                ('next_maintenance', models.DateField(blank=True, null=True, verbose_name='Keyingi texnik ko‘rik sanasi')),
                ('is_conserved', models.BooleanField(default=False, verbose_name='Konservatsiyaga olish')),
                ('conservation_reason', models.TextField(blank=True, null=True, verbose_name='Konservatsiya sababi')),
                ('voltmeter_inspection_date', models.DateField(blank=True, null=True, verbose_name='Voltmetr ko‘rik sanasi')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Javobgar shaxs')),
            ],
            options={
                'verbose_name': 'Payvandlash qurilmasi',
                'verbose_name_plural': 'Payvandlash qurilmalari',
            },
        ),
    ]
