# Generated by Django 5.1.7 on 2025-07-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heatingboiler',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='QR kod avtomatik yaratiladi', null=True, upload_to='qr_codes/', verbose_name='QR Kod'),
        ),
        migrations.AddField(
            model_name='lathemachine',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='QR kod avtomatik yaratiladi', null=True, upload_to='qr_codes/', verbose_name='QR Kod'),
        ),
        migrations.AddField(
            model_name='liftingcrane',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='QR kod avtomatik yaratiladi', null=True, upload_to='qr_codes/', verbose_name='QR Kod'),
        ),
        migrations.AddField(
            model_name='pressurevessel',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='QR kod avtomatik yaratiladi', null=True, upload_to='qr_codes/', verbose_name='QR Kod'),
        ),
        migrations.AddField(
            model_name='weldingequipment',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='QR kod avtomatik yaratiladi', null=True, upload_to='qr_codes/', verbose_name='QR Kod'),
        ),
    ]
