# Generated by Django 5.1.7 on 2025-08-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_heatingboiler_qr_code_lathemachine_qr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heatingboiler',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Joylashuv kengligi', max_digits=10, null=True, verbose_name='Kenglik'),
        ),
        migrations.AddField(
            model_name='heatingboiler',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Joylashuv uzunligi', max_digits=11, null=True, verbose_name='Uzunlik'),
        ),
        migrations.AddField(
            model_name='lathemachine',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Joylashuv kengligi', max_digits=10, null=True, verbose_name='Kenglik'),
        ),
        migrations.AddField(
            model_name='lathemachine',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Joylashuv uzunligi', max_digits=11, null=True, verbose_name='Uzunlik'),
        ),
        migrations.AddField(
            model_name='liftingcrane',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Joylashuv kengligi', max_digits=10, null=True, verbose_name='Kenglik'),
        ),
        migrations.AddField(
            model_name='liftingcrane',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Joylashuv uzunligi', max_digits=11, null=True, verbose_name='Uzunlik'),
        ),
        migrations.AddField(
            model_name='pressurevessel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Joylashuv kengligi', max_digits=10, null=True, verbose_name='Kenglik'),
        ),
        migrations.AddField(
            model_name='pressurevessel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Joylashuv uzunligi', max_digits=11, null=True, verbose_name='Uzunlik'),
        ),
        migrations.AddField(
            model_name='weldingequipment',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Joylashuv kengligi', max_digits=10, null=True, verbose_name='Kenglik'),
        ),
        migrations.AddField(
            model_name='weldingequipment',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Joylashuv uzunligi', max_digits=11, null=True, verbose_name='Uzunlik'),
        ),
    ]
