# Generated by Django 5.1.7 on 2025-08-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_heatingboiler_latitude_heatingboiler_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heatingboiler',
            name='location_address',
            field=models.CharField(blank=True, help_text='Joylashuv manzili', max_length=500, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='lathemachine',
            name='location_address',
            field=models.CharField(blank=True, help_text='Joylashuv manzili', max_length=500, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='liftingcrane',
            name='location_address',
            field=models.CharField(blank=True, help_text='Joylashuv manzili', max_length=500, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='pressurevessel',
            name='location_address',
            field=models.CharField(blank=True, help_text='Joylashuv manzili', max_length=500, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='weldingequipment',
            name='location_address',
            field=models.CharField(blank=True, help_text='Joylashuv manzili', max_length=500, verbose_name='Manzil'),
        ),
    ]
