# Generated by Django 5.1.7 on 2025-04-17 06:10

import apps.utils.get_upload_path
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('maintenance_type', models.CharField(choices=[('preventive', 'Oldini olish'), ('corrective', 'Tuzatish'), ('condition_based', 'Holatga asoslangan'), ('predictive', 'Bashoratli')], default='preventive', max_length=25, verbose_name='Xizmat turi')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, verbose_name="Ta'rif")),
                ('scheduled_date', models.DateTimeField(blank=True, null=True, verbose_name='Rejalashtirilgan sana')),
                ('estimated_duration', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Taxminiy muddat')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Bajarildi')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Bajarilgan vaqti')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_level', models.CharField(choices=[('low', 'Past'), ('medium', 'O‘rta'), ('high', 'Yuqori'), ('critical', 'Favqulodda')], default='medium', max_length=15, verbose_name='Ogohlantirish darajasi')),
                ('days_before', models.PositiveIntegerField(blank=True, default=10, null=True, verbose_name='Belgilangan sanadan bir necha kun oldin')),
                ('message', models.TextField(blank=True, verbose_name='Ogohlantirish xabari')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Yuborildi')),
                ('sent_date', models.DateTimeField(blank=True, null=True, verbose_name='Yuborilgan sana')),
            ],
            options={
                'verbose_name': 'Maintenance Warning',
                'verbose_name_plural': 'Maintenance Warnings',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Xabarnoma sarlavhasi')),
                ('message', models.TextField(blank=True, verbose_name='Xabarnoma matni')),
                ('notification_type', models.CharField(choices=[('maintenance_due', 'Texnik xizmat muddati yaqinlashmoqda'), ('maintenance_completed', 'Texnik xizmat bajarildi'), ('fault_reported', 'Nosozlik aniqlandi'), ('fault_resolved', 'Nosozlik bartaraf etildi'), ('system', 'Tizim xabarnomasi')], default='maintenance_due', max_length=25, verbose_name='Xabarnoma turi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('is_read', models.BooleanField(default=False, verbose_name='O‘qilgan')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='O‘qilgan vaqti')),
                ('sent_to_telegram', models.BooleanField(default=False, verbose_name='Telegramga yuborilgan')),
            ],
            options={
                'verbose_name': 'Xabarnoma',
                'verbose_name_plural': 'Xabarnomalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentFault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Nosozlik nomi')),
                ('description', models.TextField(blank=True, verbose_name="Ta'rifi")),
                ('severity', models.CharField(choices=[('minor', 'Yengil'), ('moderate', 'O‘rtacha'), ('major', 'Jiddiy'), ('critical', 'Favqulodda')], default='moderate', max_length=10, verbose_name='Holati')),
                ('photo', models.ImageField(upload_to=apps.utils.get_upload_path.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Rasmi')),
                ('capture_time', models.DateTimeField(blank=True, null=True, verbose_name='Suratga olish vaqti')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='Xabar berilgan vaqti')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Yechilgan')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Hal qilingan vaqt')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Nosozlik haqida izoh')),
                ('gps_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='GPS location')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Uskunalar nosozligi',
                'verbose_name_plural': 'Uskunalar nosozliklari',
            },
        ),
    ]
